# Generated by Django 4.0.6 on 2022-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
