# Generated by Django 4.0.6 on 2022-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/flowerized-site.appspot.com/o/ITEM%20IMAGES%2Fmomo.jpg?alt=media&token=bb9f6285-af13-4d36-8f41-c7027019f9d1'),
        ),
    ]
