# Generated by Django 4.0.6 on 2022-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/flowerized-site.appspot.com/o/momo.jpg?alt=media&token=d902bfc4-e239-44cc-bb89-cf9e2e20b1c5'),
        ),
    ]
