# Generated by Django 4.0.6 on 2022-09-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
