# Generated by Django 4.0.6 on 2022-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_categories_options_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Package',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
