# Generated by Django 4.0.6 on 2022-09-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_categories_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'packages',
            },
        ),
        migrations.RemoveField(
            model_name='categories',
            name='Package',
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.package'),
        ),
    ]
