# Generated by Django 3.2.14 on 2022-07-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerized_app', '0007_alter_item_itempicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirmPassword',
        ),
    ]
