# Generated by Django 3.2.14 on 2022-07-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerized_app', '0008_remove_account_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(max_length=2000, null=True, verbose_name='token'),
        ),
    ]
